M48
; DRILL file {KiCad 9.0.7-9.0.7~ubuntu24.04.1} date 2026-02-04T17:35:05-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-02-04T17:35:05-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7-9.0.7~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.850
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X133.7Y-109.685
X133.7Y-114.535
T2
X136.73Y-109.385
X136.73Y-114.835
M30
