M48
; DRILL file {KiCad 9.0.7-9.0.7~ubuntu24.04.1} date 2026-02-04T21:28:14-0500
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-02-04T21:28:14-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7-9.0.7~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0728
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0866
%
G90
G05
T1
X5.2638Y-4.3183
X5.2638Y-4.5093
T2
X5.3831Y-4.3065
X5.3831Y-4.5211
M30
